// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChatAgregado.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChatPlataformaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ChatPlataformaId", "Plataforma")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.ConsultaRecuperada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MensajeHerramientaInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Rank")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MensajeHerramientaInfoId");

                    b.ToTable("ConsultaRecuperada");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.DocumentoRecuperado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MensajeHerramientaInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Rank")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("MensajeHerramientaInfoId");

                    b.ToTable("DocumentoRecuperado");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlataformaMensajeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.ConsultaAgregado.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EmbeddingDescripcion")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.PrimitiveCollection<string>("EmbeddingTitulo")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<int>("RemoteId")
                        .HasColumnType("int");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Domain.Entities.DocumentoAgregado.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Filename")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Domain.Entities.DocumentoAgregado.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunk");
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<double>("RetryIntervalSeconds")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeHerramienta", b =>
                {
                    b.HasBaseType("Domain.Entities.ChatAgregado.Mensaje");

                    b.Property<Guid>("LlamadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("LlamadaId")
                        .IsUnique()
                        .HasFilter("[LlamadaId] IS NOT NULL");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeIA", b =>
                {
                    b.HasBaseType("Domain.Entities.ChatAgregado.Mensaje");

                    b.Property<bool?>("Calificacion")
                        .HasColumnType("bit");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MensajesIA");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeLlamadaHerramienta", b =>
                {
                    b.HasBaseType("Domain.Entities.ChatAgregado.Mensaje");

                    b.Property<string>("Argumentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PluginName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MensajesLlamadaHerramienta");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeTextoUsuario", b =>
                {
                    b.HasBaseType("Domain.Entities.ChatAgregado.Mensaje");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MensajesTextoUsuario");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeHerramientaInfo", b =>
                {
                    b.HasBaseType("Domain.Entities.ChatAgregado.MensajeHerramienta");

                    b.ToTable("MensajeHerramientaInfo");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.ConsultaRecuperada", b =>
                {
                    b.HasOne("Domain.Entities.ConsultaAgregado.Consulta", null)
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ChatAgregado.MensajeHerramientaInfo", null)
                        .WithMany("ConsultasRecuperadas")
                        .HasForeignKey("MensajeHerramientaInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.DocumentoRecuperado", b =>
                {
                    b.HasOne("Domain.Entities.DocumentoAgregado.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ChatAgregado.MensajeHerramientaInfo", null)
                        .WithMany("DocumentosRecuperados")
                        .HasForeignKey("MensajeHerramientaInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.Mensaje", b =>
                {
                    b.HasOne("Domain.Entities.ChatAgregado.Chat", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DocumentoAgregado.DocumentChunk", b =>
                {
                    b.HasOne("Domain.Entities.DocumentoAgregado.Document", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeHerramienta", b =>
                {
                    b.HasOne("Domain.Entities.ChatAgregado.MensajeLlamadaHerramienta", "Llamada")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.ChatAgregado.MensajeHerramienta", "LlamadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Llamada");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.Chat", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("Domain.Entities.DocumentoAgregado.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Domain.Entities.ChatAgregado.MensajeHerramientaInfo", b =>
                {
                    b.Navigation("ConsultasRecuperadas");

                    b.Navigation("DocumentosRecuperados");
                });
#pragma warning restore 612, 618
        }
    }
}
