name: Release on Merge to Main

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.2
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.2
        with:
          overrideConfig: |
            major-version-bump-message= \+semver:\s?(breaking|major)
            minor-version-bump-message= \+semver:\s?(feat|minor)
            patch-version-bump-message= \+semver:\s?(fix|patch)

        
      - name: Create new Git tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          NEW_TAG="v${{ env.majorMinorPatch }}"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.majorMinorPatch }}
          release_name: Release v${{ env.majorMinorPatch }}
          body: |
            Release notes for version v${{ env.majorMinorPatch }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
